# Generated by Django 4.0.3 on 2022-04-03 12:41

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('main_image_alt', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, max_length=750)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('main_image', models.ImageField(upload_to='photos/products')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('num_sold', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
