# Generated by Django 4.0.3 on 2022-04-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_cart_shipping_option'),
        ('store', '0007_alter_pages_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200, unique=True)),
                ('billing_first_name', models.CharField(max_length=50)),
                ('billing_last_name', models.CharField(max_length=50)),
                ('billing_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('billing_email', models.EmailField(max_length=100)),
                ('billing_address_line_1', models.CharField(max_length=15)),
                ('billing_address_line_2', models.CharField(blank=True, max_length=50)),
                ('billing_country', models.CharField(max_length=50)),
                ('billing_state', models.CharField(max_length=50)),
                ('billing_city', models.CharField(max_length=50)),
                ('billing_postcode', models.CharField(max_length=50)),
                ('shipping_method', models.CharField(max_length=200, null=True)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('On hold', 'On hold')], max_length=10)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship_diff_to_bill', models.BooleanField(default=False)),
                ('ship_first_name', models.CharField(blank=True, max_length=50)),
                ('ship_last_name', models.CharField(blank=True, max_length=50)),
                ('ship_phone', models.CharField(blank=True, max_length=15)),
                ('ship_email', models.EmailField(blank=True, max_length=100)),
                ('ship_address_line_1', models.CharField(blank=True, max_length=15)),
                ('ship_address_line_2', models.CharField(blank=True, max_length=50)),
                ('ship_country', models.CharField(blank=True, max_length=50)),
                ('ship_state', models.CharField(blank=True, max_length=50)),
                ('ship_city', models.CharField(blank=True, max_length=50)),
                ('ship_postcode', models.CharField(blank=True, max_length=50)),
                ('payment_intent_id', models.CharField(max_length=300)),
                ('cart_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
